name: Release a new version
on:
  release:
    types:
      - released
jobs:
  snapshot-release:
    name: Release a new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Sets up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin # Eclipse Temurin is <3
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lets ./gradlew be executable
        run: chmod +x ./gradlew

      - name: Check if Spotless finds any errors
        run: ./gradlew spotlessCheck --no-daemon

      - name: Check if project can be compiled
        run: ./gradlew compileKotlin --no-daemon

      - name: Release!
        run: ./gradlew publish -Dorg.gradle.s3.endpoint=https://s3.wasabisys.com
        env:
          NOELWARE_PUBLISHING_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          NOELWARE_PUBLISHING_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          NOELWARE_PUBLISHING_IS_SNAPSHOT: "false"
